version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/rhel9-action"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/rhel10-action"
    schedule:
      interval: "daily"

